### PR TITLE
Feature/dfs 125 showpopup

### PR DESCRIPTION
**Pull request by AleksDoesCode**
Added a lot of UI improvements and implemented a first version for recently closed orders

### CODE REVIEW

**Comment by AleksDoesCode** [comment]
Removed unused import

**Review by AnHere — CHANGES_REQUESTED** [review]
I see an error on the dashboard screen while debugging, saying duplicate keys found (open orders section). Please take a look

**Comment by AleksDoesCode** [comment]
Fixed duplicate Keys, please take a look

**Comment by AleksDoesCode** [comment]
Fixed and improved

**Comment by AleksDoesCode** [comment]
Removed unused import

**Review by AnHere — APPROVED** [review]

**Pull request merged**
